# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | upper_first }}
  {%- for commit in commits %}
    - {{ commit.message | split(pat="\\n") | first | trim }}\
      {%- if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
      {%- if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}){%- endif %}
  {%- endfor %}
{% endfor %}
"""
footer = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% for release in releases -%}
  {% if release.version and release.previous.version -%}
    [{{ release.version | trim_start_matches(pat="v") }}]: \
      {{ self::remote_url() }}/compare/{{ release.previous.version }}...{{ release.version }}
  {% elif release.previous.version -%}
    [unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}...HEAD
  {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^chore\\(release\\)", skip = true },
  { message = "^Merge ", skip = true },
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^doc", group = "Documentation" },
  { message = "^perf", group = "Changed" },
  { message = "^refactor", group = "Changed" },
  { message = "^[Aa]dd|^[Ii]mplement|^[Ss]upport", group = "Added" },
  { message = "^[Ff]ix", group = "Fixed" },
  { message = "^[Rr]emove|^[Dd]elete", group = "Removed" },
  { message = "^[Dd]oc", group = "Documentation" },
  { message = ".*", group = "Changed" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "newest"

[remote.github]
owner = "k1nz"
repo = "lanpaste"
